/**
 * Full tools catalog — every planned tool, grouped by category.
 * Source of truth for the ToolsBar dropdown navigation.
 *
 * For each tool we track:
 *   - slug: the URL after `/tools/`
 *   - label: human name shown in the dropdown
 *   - live: true if it ships in the registry today; false = "soon"
 *
 * Slugs use our new naming convention: `<category>-<thing>` (e.g. text-uppercase).
 * Once a tool is migrated under tools/<slug>/, set live: true.
 */

import { TOOL_BY_ID } from './registry';
import { isStudioDisabled } from '@/lib/studios/disabled';
import type { Category } from './registry/types';

export interface CatalogTool {
  slug: string;
  label: string;
  /** Optional explicit link (e.g. a /convert/ pair page) for tools that don't
   * live at /tools/{slug}. When set, the tool is treated as live. */
  href?: string;
}

export interface CatalogCategory {
  id: Category;
  label: string;
  icon: string;
  tools: CatalogTool[];
}

const RAW_CATALOG: CatalogCategory[] = [
  {
    id: 'image',
    label: 'Image',
    icon: 'image',
    tools: [
      { slug: 'image-face-detect', label: 'Face Detection' },
      { slug: 'image-heic-convert', label: 'HEIC → JPG' },
      { slug: 'image-text-behind', label: 'Text Behind Photo' },
      { slug: 'image-remove-metadata', label: 'Remove EXIF Metadata' },
      { slug: 'image-doc-scan', label: 'Document Scanner' },
      { slug: 'image-object-remove', label: 'Object Remover' },
      { slug: 'image-smart-cutout', label: 'Click to Cut Out' },
      { slug: 'image-blur', label: 'Blur' },
      { slug: 'image-add-shadow', label: 'Add Shadow' },
      { slug: 'image-add-text', label: 'Add Text' },
      { slug: 'dev-base64-image', label: 'Base64 ↔ Image' },
      { slug: 'image-batch-compress', label: 'Batch Compress' },
      { slug: 'image-batch-convert', label: 'Batch Convert' },
      { slug: 'image-batch-rename', label: 'Batch Rename' },
      { slug: 'image-batch-resize', label: 'Batch Resize' },
      { slug: 'image-batch-watermark', label: 'Batch Watermark' },
      { slug: 'image-border', label: 'Border' },
      { slug: 'image-brightness', label: 'Brightness' },
      { slug: 'image-compare', label: 'Compare Images' },
      { slug: 'image-compress', label: 'Compress' },
      { slug: 'image-contrast', label: 'Contrast' },
      { slug: 'image-convert-format', label: 'Convert Format' },
      { slug: 'image-collage', label: 'Create Collage' },
      { slug: 'image-crop', label: 'Crop' },
      { slug: 'image-duotone', label: 'Duotone' },
      { slug: 'image-color-extract', label: 'Extract Colors' },
      { slug: 'image-exif', label: 'Photo Metadata' },
      { slug: 'image-flip', label: 'Flip' },
      { slug: 'image-frame', label: 'Frame' },
      { slug: 'image-grayscale', label: 'Grayscale' },
      { slug: 'image-hue', label: 'Hue' },
      { slug: 'image-info', label: 'Image Info' },
      { slug: 'image-invert', label: 'Invert Colors' },
      { slug: 'image-merge', label: 'Merge Images' },
      { slug: 'image-denoise', label: 'Denoise' },
      { slug: 'image-ocr', label: 'Image → Text (OCR)' },
      { slug: 'image-perspective', label: 'Perspective Correct' },
      { slug: 'image-pixelate', label: 'Pixelate' },
      { slug: 'image-placeholder', label: 'Generate Placeholder' },
      { slug: 'image-remove-bg', label: 'Remove Background' },
      { slug: 'image-resize', label: 'Resize' },
      { slug: 'image-rotate', label: 'Rotate' },
      { slug: 'image-round-corners', label: 'Round Corners' },
      { slug: 'image-saturation', label: 'Saturation' },
      { slug: 'image-sepia', label: 'Sepia' },
      { slug: 'image-sharpen', label: 'Sharpen' },
      { slug: 'image-split', label: 'Split' },
      { slug: 'image-upscale', label: 'Upscale' },
      { slug: 'image-vignette', label: 'Vignette' },
      { slug: 'image-vintage', label: 'Vintage' },
      { slug: 'image-watermark', label: 'Watermark' },
    ],
  },
  {
    id: 'audio',
    label: 'Audio',
    icon: 'music-2',
    tools: [
      { slug: 'audio-trim', label: 'Trim' },
      { slug: 'audio-merge', label: 'Merge' },
      { slug: 'audio-split', label: 'Split' },
      { slug: 'audio-compress', label: 'Compress' },
      { slug: 'audio-normalize', label: 'Normalize' },
      { slug: 'audio-reverse', label: 'Reverse' },
      { slug: 'audio-loop', label: 'Loop' },
      { slug: 'audio-speed', label: 'Change Speed' },
      { slug: 'audio-pitch', label: 'Change Pitch' },
      { slug: 'audio-tempo', label: 'Change Tempo' },
      { slug: 'audio-pan', label: 'Stereo Pan' },
      { slug: 'audio-stereo-width', label: 'Stereo Width' },
      { slug: 'audio-fade-in', label: 'Fade In' },
      { slug: 'audio-fade-out', label: 'Fade Out' },
      { slug: 'audio-volume', label: 'Adjust Volume' },
      { slug: 'audio-remove-silence', label: 'Remove Silence' },
      { slug: 'audio-remove-noise', label: 'Remove Noise' },
      { slug: 'audio-echo', label: 'Echo' },
      { slug: 'audio-reverb', label: 'Reverb' },
      { slug: 'audio-bass-boost', label: 'Bass Boost' },
      { slug: 'audio-treble-boost', label: 'Treble Boost' },
      { slug: 'audio-equalizer', label: 'Equalizer' },
      { slug: 'audio-vocal-remover', label: 'Vocal Remover' },
      { slug: 'video-extract-audio', label: 'Extract from Video' },
      { slug: 'audio-mono-to-stereo', label: 'Mono → Stereo' },
      { slug: 'audio-stereo-to-mono', label: 'Stereo → Mono' },
      { slug: 'audio-convert-format', label: 'Convert Format' },
      { slug: 'audio-to-text', label: 'Speech → Text' },
      { slug: 'audio-text-to-speech', label: 'Text → Speech' },
      { slug: 'audio-waveform', label: 'Generate Waveform' },
    ],
  },
  {
    id: 'video',
    label: 'Video',
    icon: 'film',
    tools: [
      { slug: 'video-screen-record', label: 'Screen Recorder' },
      { slug: 'video-webcam-test', label: 'Webcam & Mic Test' },
      { slug: 'video-reframe', label: 'Vertical Reframe' },
      { slug: 'video-trim', label: 'Trim' },
      { slug: 'video-merge', label: 'Merge' },
      { slug: 'video-split', label: 'Split' },
      { slug: 'video-crop', label: 'Crop' },
      { slug: 'video-rotate', label: 'Rotate' },
      { slug: 'video-flip', label: 'Flip' },
      { slug: 'video-resize', label: 'Resize' },
      { slug: 'video-compress', label: 'Compress' },
      { slug: 'video-convert-format', label: 'Convert Format' },
      { slug: 'video-bitrate', label: 'Change Bitrate' },
      { slug: 'video-extract-audio', label: 'Extract Audio' },
      { slug: 'video-extract-segment', label: 'Extract Segment' },
      { slug: 'video-extract-frames', label: 'Extract Frames' },
      { slug: 'video-mute', label: 'Remove Audio' },
      { slug: 'video-remove-segment', label: 'Remove Segment' },
      { slug: 'video-add-audio', label: 'Add Audio' },
      { slug: 'video-add-subtitles', label: 'Add Subtitles' },
      { slug: 'video-watermark', label: 'Add Watermark' },
      { slug: 'video-add-text', label: 'Add Text' },
      { slug: 'video-brightness', label: 'Adjust Brightness' },
      { slug: 'video-speed', label: 'Adjust Speed' },
      { slug: 'video-volume', label: 'Adjust Volume' },
      { slug: 'video-blur', label: 'Blur' },
      { slug: 'video-reverse', label: 'Reverse' },
      { slug: 'video-loop', label: 'Loop' },
      { slug: 'video-to-gif', label: 'Video → GIF' },
      { slug: 'video-gif-to-video', label: 'GIF → Video' },
      { slug: 'images-to-video', label: 'Photos → Video' },
      { slug: 'video-thumbnail', label: 'Generate Thumbnail' },
    ],
  },
  {
    id: 'pdf',
    label: 'PDF',
    icon: 'file-text',
    tools: [
      { slug: 'pdf-sign', label: 'Sign PDF' },
      { slug: 'pdf-merge', label: 'Merge' },
      { slug: 'pdf-split', label: 'Split' },
      { slug: 'pdf-compress', label: 'Compress' },
      { slug: 'pdf-to-images', label: 'PDF → Images' },
      { slug: 'images-to-pdf', label: 'Images → PDF' },
      { slug: 'pdf-rotate', label: 'Rotate' },
      { slug: 'pdf-delete-pages', label: 'Delete Pages' },
      { slug: 'pdf-extract-pages', label: 'Extract Pages' },
      { slug: 'pdf-page-numbers', label: 'Add Page Numbers' },
      { slug: 'pdf-watermark', label: 'Add Watermark' },
      { slug: 'pdf-reorder', label: 'Reorder Pages' },
      { slug: 'pdf-protect', label: 'Protect with Password' },
      { slug: 'pdf-unlock', label: 'Unlock' },
      { slug: 'pdf-ocr', label: 'OCR (Text from PDF)' },
      { slug: 'pdf-to-text', label: 'PDF → Text' },
      { slug: 'pdf-fill-form', label: 'Fill Form' },
      { slug: 'pdf-info', label: 'PDF Info' },
    ],
  },
  {
    id: 'text',
    label: 'Text',
    icon: 'type',
    tools: [
      { slug: 'text-uppercase', label: 'UPPERCASE' },
      { slug: 'text-lowercase', label: 'lowercase' },
      { slug: 'text-title-case', label: 'Title Case' },
      { slug: 'text-sentence-case', label: 'Sentence case' },
      { slug: 'text-camel-case', label: 'camelCase' },
      { slug: 'text-pascal-case', label: 'PascalCase' },
      { slug: 'text-snake-case', label: 'snake_case' },
      { slug: 'text-kebab-case', label: 'kebab-case' },
      { slug: 'text-reverse', label: 'Reverse Text' },
      { slug: 'text-word-counter', label: 'Word Counter' },
      { slug: 'text-base64', label: 'Base64 Encode / Decode' },
      { slug: 'text-url-encode', label: 'URL Encode' },
      { slug: 'text-url-decode', label: 'URL Decode' },
      { slug: 'text-html-encode', label: 'HTML Entities' },
      { slug: 'text-rot13', label: 'ROT13' },
      { slug: 'text-add-prefix', label: 'Add Prefix' },
      { slug: 'text-add-suffix', label: 'Add Suffix' },
      { slug: 'text-add-line-numbers', label: 'Add Line Numbers' },
      { slug: 'text-add-line-breaks', label: 'Add Line Breaks' },
      { slug: 'text-remove-empty-lines', label: 'Remove Empty Lines' },
      { slug: 'text-remove-duplicates', label: 'Remove Duplicates' },
      { slug: 'text-remove-extra-spaces', label: 'Remove Extra Spaces' },
      { slug: 'text-remove-numbers', label: 'Remove Numbers' },
      { slug: 'text-remove-letters', label: 'Remove Letters' },
      { slug: 'text-sort-lines', label: 'Sort Lines' },
      { slug: 'text-reverse-lines', label: 'Reverse Line Order' },
      { slug: 'text-find-replace', label: 'Find & Replace' },
      { slug: 'text-regex', label: 'Regex Find & Replace' },
      { slug: 'text-extract-emails', label: 'Extract Emails' },
      { slug: 'text-extract-urls', label: 'Extract URLs' },
      { slug: 'text-extract-numbers', label: 'Extract Numbers' },
      { slug: 'text-extract-phone', label: 'Extract Phone Numbers' },
      { slug: 'text-extract-hashtags', label: 'Extract Hashtags' },
      { slug: 'text-extract-mentions', label: 'Extract Mentions' },
      { slug: 'text-keyword-density', label: 'Keyword Density' },
      { slug: 'text-readability', label: 'Readability Score' },
    ],
  },
  {
    id: 'dev',
    label: 'Dev',
    icon: 'code-2',
    tools: [
      { slug: 'dev-json-format', label: 'JSON Formatter' },
      { slug: 'dev-json-minify', label: 'JSON Minify' },
      { slug: 'dev-json-validate', label: 'JSON Validator' },
      { slug: 'dev-json-to-yaml', label: 'JSON → YAML' },
      { slug: 'dev-yaml-to-json', label: 'YAML → JSON' },
      { slug: 'dev-xml-format', label: 'XML Formatter' },
      { slug: 'dev-html-format', label: 'HTML Formatter' },
      { slug: 'dev-css-format', label: 'CSS Formatter' },
      { slug: 'dev-js-format', label: 'JS Formatter' },
      { slug: 'dev-sql-format', label: 'SQL Formatter' },
      { slug: 'dev-uuid', label: 'UUID Generator' },
      { slug: 'dev-hash', label: 'Hash (MD5/SHA)' },
      { slug: 'dev-bcrypt', label: 'Bcrypt' },
      { slug: 'dev-hmac', label: 'HMAC' },
      { slug: 'dev-jwt-decode', label: 'JWT Decoder' },
      { slug: 'dev-slug', label: 'Slug Generator' },
      { slug: 'dev-lorem', label: 'Lorem Ipsum' },
      { slug: 'dev-regex', label: 'Regex Tester' },
      { slug: 'dev-diff', label: 'Diff Checker' },
      { slug: 'dev-hex-viewer', label: 'Hex Viewer' },
      { slug: 'dev-password', label: 'Password Generator' },
      { slug: 'dev-totp', label: 'TOTP Generator' },
      { slug: 'dev-base64-image', label: 'Image ↔ Base64' },
      { slug: 'gen-gradient', label: 'CSS Gradient' },
      { slug: 'gen-box-shadow', label: 'CSS Box Shadow' },
      { slug: 'gen-flexbox', label: 'CSS Flexbox' },
      { slug: 'gen-grid', label: 'CSS Grid' },
      { slug: 'gen-animation', label: 'CSS Animation' },
      { slug: 'gen-glassmorphism', label: 'Glassmorphism' },
    ],
  },
  {
    id: 'convert',
    label: 'Convert',
    icon: 'replace',
    tools: [
      { slug: 'convert-anything', label: 'Convert Anything' },
      { slug: 'archive-extract', label: 'Extract Archive' },
      { slug: 'archive-zip', label: 'Create ZIP' },
      { slug: 'model-3d-convert', label: '3D Model Converter' },
      { slug: 'sheet-convert', label: 'Spreadsheet Converter' },
      { slug: 'doc-convert', label: 'Document Converter' },
      { slug: 'slides-convert', label: 'Slides Converter' },
      { slug: 'ebook-convert', label: 'EPUB Converter' },
      { slug: 'cad-convert', label: 'CAD to Mesh' },
      { slug: 'convert-hub', label: 'All conversions', href: '/convert' },
      { slug: 'convert-png-to-jpg', label: 'PNG → JPG', href: '/convert/png-to-jpg' },
      { slug: 'convert-webp-to-jpg', label: 'WebP → JPG', href: '/convert/webp-to-jpg' },
      { slug: 'convert-svg-to-png', label: 'SVG → PNG', href: '/convert/svg-to-png' },
      { slug: 'convert-mp4-to-audio', label: 'MP4 → Audio', href: '/convert/mp4-to-audio' },
      { slug: 'convert-wav-to-mp3', label: 'WAV → MP3', href: '/convert/wav-to-mp3' },
      { slug: 'convert-pdf-to-jpg', label: 'PDF → JPG', href: '/convert/pdf-to-jpg' },
      { slug: 'convert-jpg-to-pdf', label: 'JPG → PDF', href: '/convert/jpg-to-pdf' },
      { slug: 'convert-mp3-to-text', label: 'MP3 → Text', href: '/convert/mp3-to-txt' },
    ],
  },
  {
    id: 'calc',
    label: 'Calc',
    icon: 'calculator',
    tools: [
      { slug: 'calc-basic', label: 'Basic Calculator' },
      { slug: 'calc-bmi', label: 'BMI' },
      { slug: 'calc-percent', label: 'Percentage' },
      { slug: 'calc-age', label: 'Age' },
      { slug: 'calc-loan', label: 'Loan' },
      { slug: 'calc-tip', label: 'Tip' },
      { slug: 'calc-date', label: 'Date Difference' },
      { slug: 'calc-time', label: 'Time' },
      { slug: 'calc-hex', label: 'Hex Calculator' },
      { slug: 'calc-binary', label: 'Binary Calculator' },
      { slug: 'calc-scientific', label: 'Scientific' },
      { slug: 'calc-power', label: 'Power / Energy' },
      { slug: 'calc-temp', label: 'Temperature' },
      { slug: 'calc-matrix', label: 'Matrix' },
      { slug: 'calc-derivative', label: 'Derivative' },
      { slug: 'calc-integral', label: 'Integral' },
      { slug: 'calc-equation', label: 'Equation Solver' },
      { slug: 'calc-latex', label: 'LaTeX Renderer' },
    ],
  },
  {
    id: 'generator',
    label: 'Generate',
    icon: 'sparkles',
    tools: [
      { slug: 'gen-qr-code', label: 'QR Code' },
      { slug: 'gen-barcode', label: 'Barcode' },
      { slug: 'gen-color-palette', label: 'Color Palette' },
      { slug: 'gen-gradient', label: 'Gradient' },
      { slug: 'gen-mesh-gradient', label: 'Mesh Gradient' },
      { slug: 'gen-color-converter', label: 'Color Converter' },
      { slug: 'gen-color-contrast', label: 'Contrast Checker' },
      { slug: 'gen-random-data', label: 'Random Data' },
      { slug: 'gen-lorem-image', label: 'Placeholder Image' },
      { slug: 'gen-invoice', label: 'Invoice' },
      { slug: 'gen-resume', label: 'Resume' },
      { slug: 'gen-favicon', label: 'Favicon' },
      { slug: 'gen-css-filter', label: 'CSS Filter' },
      { slug: 'gen-css-text-shadow', label: 'CSS Text Shadow' },
      { slug: 'gen-css-transform', label: 'CSS Transform' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: 'piggy-bank',
    tools: [
      { slug: 'finance-currency', label: 'Currency Converter' },
      { slug: 'finance-budget', label: 'Budget Planner' },
      { slug: 'finance-mortgage', label: 'Mortgage' },
      { slug: 'finance-loan-comparison', label: 'Loan Comparison' },
      { slug: 'finance-investment', label: 'Investment' },
      { slug: 'finance-retirement', label: 'Retirement' },
      { slug: 'finance-savings', label: 'Savings' },
      { slug: 'finance-tax', label: 'Tax' },
    ],
  },
  {
    id: 'time',
    label: 'Time',
    icon: 'clock',
    tools: [
      { slug: 'time-unix-timestamp', label: 'Unix Timestamp' },
      { slug: 'time-timezone', label: 'Timezone Converter' },
      { slug: 'time-cron', label: 'Cron Expression' },
      { slug: 'time-date-diff', label: 'Date Difference' },
      { slug: 'time-countdown', label: 'Countdown' },
      { slug: 'time-iso-8601', label: 'ISO 8601' },
      { slug: 'time-world-clock', label: 'World Clock' },
    ],
  },
  {
    id: 'seo',
    label: 'SEO',
    icon: 'search-check',
    tools: [
      { slug: 'seo-meta-tag', label: 'Meta Tag Analyzer' },
      { slug: 'seo-robots-txt', label: 'Robots.txt Generator' },
      { slug: 'seo-sitemap', label: 'Sitemap Generator' },
      { slug: 'seo-open-graph', label: 'Open Graph Preview' },
      { slug: 'seo-twitter-card', label: 'Twitter Card Preview' },
      { slug: 'seo-structured-data', label: 'Structured Data' },
      { slug: 'seo-headings', label: 'Heading Structure' },
      { slug: 'text-keyword-density', label: 'Keyword Density' },
    ],
  },
  {
    id: 'ip',
    label: 'Network',
    icon: 'network',
    tools: [
      { slug: 'net-speed-test', label: 'Internet Speed Test' },
      { slug: 'net-my-ip', label: 'My IP Address' },
      { slug: 'net-ip-lookup', label: 'IP Lookup' },
      { slug: 'net-ssl', label: 'SSL Checker' },
      { slug: 'net-ports', label: 'Port Checker' },
      { slug: 'net-ping', label: 'Ping (Latency)' },
      { slug: 'net-dns', label: 'DNS Lookup' },
      { slug: 'net-whois', label: 'Domain Lookup' },
      { slug: 'net-cidr', label: 'CIDR Calculator' },
      { slug: 'net-subnet', label: 'Subnet Calculator' },
      { slug: 'net-headers', label: 'HTTP Headers' },
      { slug: 'net-mac', label: 'MAC Lookup' },
      { slug: 'net-ua', label: 'User Agent' },
    ],
  },
  {
    id: 'game',
    label: 'Game',
    icon: 'gamepad-2',
    tools: [
      { slug: 'game-gacha', label: 'Gacha Simulator' },
      { slug: 'game-drop-rate', label: 'Drop Rate Calculator' },
      { slug: 'game-loadout', label: 'Loadout Randomizer' },
      { slug: 'game-username', label: 'Username Generator' },
      { slug: 'game-name', label: 'Gaming Name' },
      { slug: 'game-character', label: 'Character Name' },
      { slug: 'game-fantasy', label: 'Fantasy Name' },
      { slug: 'game-sci-fi', label: 'Sci-Fi Name' },
      { slug: 'game-guild', label: 'Guild Name' },
      { slug: 'game-clan', label: 'Clan Name' },
      { slug: 'game-team', label: 'Team Name' },
      { slug: 'game-weapon', label: 'Weapon Name' },
      { slug: 'game-spell', label: 'Spell Name' },
      { slug: 'game-quest', label: 'Quest Name' },
      { slug: 'game-dice', label: 'Dice Roller' },
      { slug: 'game-coin', label: 'Coin Flip' },
      { slug: 'game-picker', label: 'Random Picker' },
      { slug: 'game-loot', label: 'Loot Box' },
      { slug: 'game-dps', label: 'DPS Calculator' },
      { slug: 'game-xp', label: 'XP Calculator' },
      { slug: 'game-dpi', label: 'DPI Calculator' },
      { slug: 'game-fov', label: 'FOV Calculator' },
      { slug: 'game-sensitivity', label: 'Sensitivity Converter' },
      { slug: 'game-aspect-ratio', label: 'Aspect Ratio' },
      { slug: 'game-crosshair', label: 'Crosshair' },
      { slug: 'game-colorblind', label: 'Colorblind Simulator' },
    ],
  },
  {
    id: 'gis',
    label: 'GIS',
    icon: 'globe',
    tools: [
      { slug: 'gis-coords', label: 'Coordinate Converter' },
      { slug: 'gis-distance', label: 'Distance Calculator' },
      { slug: 'gis-geojson', label: 'GeoJSON Viewer' },
      { slug: 'gis-kml', label: 'KML → GeoJSON' },
      { slug: 'gis-utm', label: 'UTM Converter' },
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icon: 'share-2',
    tools: [
      { slug: 'social-resize', label: 'Social Media Resizer' },
      { slug: 'gen-favicon', label: 'Favicon' },
      { slug: 'social-og', label: 'OG Image Creator' },
      { slug: 'social-avatar', label: 'Profile Picture Maker' },
      { slug: 'social-banner', label: 'Banner Cover Maker' },
    ],
  },
  {
    id: 'font',
    label: 'Font',
    icon: 'type-outline',
    tools: [
      { slug: 'font-preview', label: 'Preview' },
      { slug: 'font-convert', label: 'Convert' },
      { slug: 'font-inspect', label: 'Inspector' },
      { slug: 'font-web', label: 'Web Font Generator' },
      { slug: 'font-subset', label: 'Subset Creator' },
    ],
  },
  {
    id: 'subtitle',
    label: 'Subtitle',
    icon: 'captions',
    tools: [
      { slug: 'subtitle-generate', label: 'Auto Subtitle Generator' },
      { slug: 'subtitle-character-counter', label: 'Character Counter' },
      { slug: 'subtitle-cleaner',           label: 'Clean & Normalize' },
      { slug: 'subtitle-fps-converter',     label: 'FPS Converter' },
      { slug: 'subtitle-merger',            label: 'Merge' },
      { slug: 'subtitle-splitter',          label: 'Split at Time' },
      { slug: 'subtitle-style-editor',      label: 'Style Editor' },
      { slug: 'subtitle-sync-fixer',        label: 'Sync Fixer' },
      { slug: 'subtitle-timing-shifter',    label: 'Timing Shifter' },
      { slug: 'subtitle-to-plain-text',     label: 'Subtitle → Text' },
      { slug: 'subtitle-translator-prep',   label: 'Translator Prep' },
    ],
  },
];

/** Brand-disabled tools (lib/studios/disabled.ts) never appear, not even as "soon". */
export const CATALOG: CatalogCategory[] = RAW_CATALOG.map((c) => ({
  ...c,
  tools: c.tools.filter((t) => !isStudioDisabled(t.slug)),
}));

/** Total tool count across the catalog (live + planned). */
export const TOTAL_TOOLS = CATALOG.reduce((n, c) => n + c.tools.length, 0);

/** Number of tools currently shipped (have a manifest in the registry or an explicit href). */
export function liveCount(category: CatalogCategory): number {
  return category.tools.filter((t) => !!t.href || TOOL_BY_ID.has(t.slug)).length;
}

export function isLive(slug: string): boolean {
  return TOOL_BY_ID.has(slug);
}

/** True if a catalog tool is reachable — either a registered tool or an explicit link. */
export function isToolLive(tool: CatalogTool): boolean {
  return !!tool.href || TOOL_BY_ID.has(tool.slug);
}

/** Resolve the link target for a catalog tool. */
export function toolHref(tool: CatalogTool): string {
  return tool.href ?? `/tools/${tool.slug}`;
}
