#!/usr/bin/env node
/**
 * APP VARIANT (generated by mk_app_sweep.py from live_sweep.mjs — edit that, not this):
 * runs inside the Xonvert Android app's WebView over CDP (env APP_CDP, e.g. http://127.0.0.1:9471),
 * files go in through window.__xonvertAppEvent (the share-in path) and results come out as the
 * app bridge's saveFile messages; each native Save/Share sheet is closed with adb BACK.
 *
 * Live breakage sweep: visits EVERY /tools/<id> page (from sitemap.xml) and every indexable
 * /convert/<pair> page, records load health, and where a sample fits the tool's `accepts`
 * uploads it, presses the obvious action button and validates the download.
 *
 *   node scripts/live_sweep.mjs [baseUrl=https://xonvert.com]
 *   env SAMPLES_DIR   (default /root/cadtest/samples; scripts/live_e2e_samples.sh fills it, plus test.jpg)
 *   env CHROMIUM_PATH (default /root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome)
 *   env REPO          (default: this script's repo) - read for tools/<id>/manifest.ts `accepts`
 *   env OUT_JSON      (default /root/cadtest/sweep.json)
 *   env ONLY          (optional regex over the path, e.g. "^/tools/image-")
 *   env CONCURRENCY   (default 3)
 * In WSL without IPv6 also set NODE_OPTIONS=--dns-result-order=ipv4first.
 * Status per page: OK | LOAD-ERROR | NO-UI | UPLOAD-FAIL | UPLOAD-OK | SKIPPED (+ reason).
 * Exit 1 when any page is LOAD-ERROR, NO-UI or UPLOAD-FAIL.
 */
import { chromium } from 'playwright-core';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

// ---- app bridge helpers ----
const hookBridge = (page) => page.evaluate(() => {
  if (window.__xvHooked || !window.XonvertBridge) return !!window.XonvertBridge;
  // On Android XonvertBridge is a Java-bound object: assigning over its method is silently
  // ignored, so replace the whole object with a recording proxy.
  const real = window.XonvertBridge;
  window.__msgs = [];
  const proxy = { postMessage: (m) => { window.__msgs.push(m); return real.postMessage(m); } };
  try { window.XonvertBridge = proxy; } catch (e) { return 'readonly'; }
  window.__xvHooked = true;
  return window.XonvertBridge === proxy ? true : 'not-replaced';
}).catch(() => false);
const appDeliver = async (page, files) => {
  const payload = files.map((f) => ({ name: path.basename(f), mime: mimeOf(f), data: fs.readFileSync(f).toString('base64') }));
  await page.evaluate((fl) => window.__xonvertAppEvent && window.__xonvertAppEvent({ type: 'files', files: fl }), payload);
};
const mimeOf = (f) => ({ png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif', heic: 'image/heic',
  svg: 'image/svg+xml', pdf: 'application/pdf', wav: 'audio/wav', mp3: 'audio/mpeg', mp4: 'video/mp4', mov: 'video/quicktime',
  mkv: 'video/x-matroska', avi: 'video/x-msvideo', txt: 'text/plain', csv: 'text/csv', json: 'application/json', md: 'text/markdown',
  srt: 'application/x-subrip', vtt: 'text/vtt', zip: 'application/zip', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  epub: 'application/epub+zip', ttf: 'font/ttf', otf: 'font/otf' })[path.extname(f).slice(1).toLowerCase()] || 'application/octet-stream';
const appSaved = async (page) => {
  const m = await page.evaluate(() => {
    for (const raw of window.__msgs || []) { try { const x = JSON.parse(raw); if (x.type === 'saveFile') return { name: x.name, data: x.data }; } catch {} }
    return null;
  }).catch(() => null);
  if (!m) return null;
  const buf = Buffer.from(m.data, 'base64');
  return { buf, suggestedFilename: () => m.name };
};
const closeSheet = () => { try { execFileSync(ADB, ['shell', 'input', 'keyevent', 'KEYCODE_BACK'], { timeout: 8000 }); } catch {} };

const BASE = (process.argv[2] || 'https://xonvert.com').replace(/\/$/, '');
const ORIGIN = new URL(BASE).origin;
const SAMPLES = process.env.SAMPLES_DIR || '/root/cadtest/samples';
const CHROME = process.env.CHROMIUM_PATH || '/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome';
const REPO = process.env.REPO || path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_JSON = process.env.OUT_JSON || '/root/cadtest/sweep.json';
const ONLY = process.env.ONLY ? new RegExp(process.env.ONLY) : null;
// 2, not 3: at 3 the sweep's own bursts tripped the per-IP /api/tool-key limit.
const CONCURRENCY = 1; // one WebView
const APP_CDP = process.env.APP_CDP || 'http://127.0.0.1:9471';
const ADB = process.env.ADB || '/mnt/c/science/android-sdk/platform-tools/adb.exe';
let APP_PAGE = null;
// Tools that need clicks ON the canvas before the action enables (no generic driver).
const INTERACTIVE = new Set(['image-smart-cutout']);
const UI_TIMEOUT = 15_000;
const DL_TIMEOUT = 45_000;
const DL_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'xonvert-sweep-'));

// Samples in preference order: first one the tool accepts wins.
const SAMPLE_TYPES = [
  { file: 'test.png',         mime: 'image/png',       exts: ['png'] },
  { file: 'test.jpg',         mime: 'image/jpeg',      exts: ['jpg', 'jpeg'] },
  { file: 'two-page.pdf',     mime: 'application/pdf', exts: ['pdf'] },
  { file: 'tone.wav',         mime: 'audio/wav',       exts: ['wav'], alt: ['audio/x-wav'] },
  { file: 'clip.mp4',         mime: 'video/mp4',       exts: ['mp4'] },
  { file: 'box.obj',          mime: 'model/obj',       exts: ['obj'] },
  { file: 'box.fbx',          mime: 'model/fbx',       exts: ['fbx'] },
  { file: 'as1-oc-214.step',  mime: 'model/step',      exts: ['step', 'stp'] },
  { file: 'example_2000.dwg', mime: 'image/vnd.dwg',   exts: ['dwg'] },
  // Extra samples (scripts/live_e2e_samples.sh) for the tools the first sweeps could not feed.
  { file: 'test.webp',        mime: 'image/webp',      exts: ['webp'] },
  { file: 'anim.gif',         mime: 'image/gif',       exts: ['gif'] },
  { file: 'example.heic',     mime: 'image/heic',      exts: ['heic', 'heif'], alt: ['image/heif'] },
  { file: 'test.svg',         mime: 'image/svg+xml',   exts: ['svg'] },
  { file: 'tone.mp3',         mime: 'audio/mpeg',      exts: ['mp3'], alt: ['audio/mp3'] },
  { file: 'clip.mov',         mime: 'video/quicktime', exts: ['mov'] },
  { file: 'clip.mkv',         mime: 'video/x-matroska', exts: ['mkv'] },
  { file: 'clip.avi',         mime: 'video/x-msvideo', exts: ['avi'] },
  { file: 'test.docx',        mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', exts: ['docx'] },
  { file: 'test.xlsx',        mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', exts: ['xlsx'] },
  { file: 'test.pptx',        mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', exts: ['pptx'] },
  { file: 'test.epub',        mime: 'application/epub+zip', exts: ['epub'] },
  { file: 'test.zip',         mime: 'application/zip', exts: ['zip'], alt: ['application/x-zip-compressed'] },
  { file: 'lato.ttf',         mime: 'font/ttf',        exts: ['ttf'], alt: ['application/x-font-ttf'] },
  { file: 'source.otf',       mime: 'font/otf',        exts: ['otf'] },
  { file: 'test.srt',         mime: 'application/x-subrip', exts: ['srt'], alt: ['text/srt'] },
  { file: 'test.vtt',         mime: 'text/vtt',        exts: ['vtt'] },
  { file: 'test.csv',         mime: 'text/csv',        exts: ['csv'] },
  { file: 'test.json',        mime: 'application/json', exts: ['json'] },
  { file: 'test.md',          mime: 'text/markdown',   exts: ['md', 'markdown'] },
  { file: 'test.txt',         mime: 'text/plain',      exts: ['txt'] },
].filter((s) => fs.existsSync(path.join(SAMPLES, s.file)));

// Second file for tools whose input is `multiple` (merge/combine/compare), by first sample.
const SECOND_FILE = { 'two-page.pdf': 'one-page.pdf', 'tone.wav': 'tone2.wav', 'test.png': 'test.jpg', 'clip.mp4': 'clip.mp4', 'test.srt': 'test.vtt' };

// Per-tool action overrides: the tool's real "do it" button when its label is not
// covered by ACTION_RE (texts collected from the live pages by this sweep).
// Each entry still passes NOT_ACTION_RE, so it can never press a purchase/share button.
const ACTION_OVERRIDE = {};

// Per-tool PREP, run after upload and before the action: these tools start on a neutral
// default (0 semitones, 1x, 0 dB, no pages, no password, no audio) that keeps the action
// button disabled. Each step is best-effort; a failure is recorded in rec.prepError.
const clickChip = (label) => async (page) => page.locator('button:visible', { hasText: label }).first().click({ timeout: 5000 });
const PREP = {
  'audio-pitch': clickChip(/^\s*\+7\s*$/),
  'audio-speed': clickChip(/^\s*1\.5×\s*$/),
  'video-speed': clickChip(/^\s*1\.5×\s*$/),
  'video-volume': clickChip(/^\s*\+6\s*$/),
  'pdf-delete-pages': async (page) => page.locator('input[placeholder="2, 5-7, 10"]').fill('2'),
  'pdf-protect': async (page) => {
    await page.locator('input[placeholder="Enter a password"]').fill('qa-sweep-1');
    await page.locator('input[placeholder="Re-enter the password"]').fill('qa-sweep-1');
  },
  'video-add-audio': async (page) => {
    const inputs = page.locator('input[type=file]');
    await inputs.nth((await inputs.count()) - 1).setInputFiles(path.join(SAMPLES, 'tone.wav'));
  },
};
// alert()/confirm() text that means the action failed (tools that report errors by dialog).
const RED_ERR_RE = /fail|error|could not|couldn't|unable|unsupported|invalid|too (large|big)|not supported/i;
const DIALOG_FAIL_RE = /fail|error|could not|couldn't|unable/i;
// Labels seen on the live pages that ACTION_RE misses ("MUTE & DOWNLOAD", "BUILD PDF", "ADD ECHO",
// "SHIFT PITCH", "RE-ENCODE", "Transcribe", ...). Checked in addition to ACTION_RE.
const ACTION_EXTRA_RE = /(&\s*download\b|^build\b|^add (echo|audio|numbers|text|watermark)\b|^shift pitch|^change (speed|tempo)|^apply volume|^re-encode|^loop$|^dub video|^scan$|^transcribe$|^enlarge\b|^reframe$|^compile gif|^translate to\b|^read again$)/i;

const ACTION_RE = /^(convert|compress|apply|extract|merge|export|process|download|save|generate|render|resize|crop|rotate|split|encode|run|start|create|make|optimi[sz]e|remove|flip|trim|cut|join|combine|enhance|upscale|blur|sharpen|protect|unlock|sign|watermark|reverse|normalize|mix|denoise)/i;
// Never press anything that starts an account, a purchase or a share.
const NOT_ACTION_RE = /change file|replace|add more|clear|reset|remove file|pin|search|upgrade|sign in|sign up|log in|register|subscribe|buy|checkout|pay|pro\b|share|invite|cancel|back|sign out|log out|logout|delete account/i;
const HW_RE = /\b(camera|webcam|microphone|record (your|from)|mic\b|screen record)/i;

// Studios intentionally disabled on this brand (they 307 to /tools); stale CDN sitemaps still list them.
const DISABLED = new Set((() => { try { return JSON.parse(fs.readFileSync(path.join(REPO, 'lib/studios/disabled-ids.json'), 'utf8')).ids || []; } catch { return []; } })());

// ---------- manifests ----------
function readAccepts(id) {
  const f = path.join(REPO, 'tools', id, 'manifest.ts');
  if (!fs.existsSync(f)) return null;
  const s = fs.readFileSync(f, 'utf8');
  const m = s.match(/accepts:\s*\[([^\]]*)\]/);
  if (!m) return null;
  return [...m[1].matchAll(/'([^']+)'|"([^"]+)"/g)].map((x) => (x[1] || x[2]).toLowerCase());
}
function acceptsSample(accepts, s) {
  return accepts.some((a) => {
    if (a.startsWith('.')) return s.exts.includes(a.slice(1));
    if (a.endsWith('/*')) return s.mime.startsWith(a.slice(0, -1));
    return a === s.mime || (s.alt || []).includes(a) || s.exts.some((e) => a.endsWith('/' + e));
  });
}
// Tools that need specific content, not just the right type (OCR finds nothing in test.png).
const SAMPLE_OVERRIDE = { '/tools/image-ocr': { file: 'ocr.png', mime: 'image/png', exts: ['png'] } };
function pickSample(url, accepts) {
  const o = SAMPLE_OVERRIDE[url];
  if (o && fs.existsSync(path.join(SAMPLES, o.file))) return o;
  const pair = url.match(/^\/convert\/([a-z0-9]+)-to-([a-z0-9]+)$/);
  if (pair) return SAMPLE_TYPES.find((s) => s.exts.includes(pair[1])) || null;
  if (!accepts || !accepts.length) return null;
  return SAMPLE_TYPES.find((s) => acceptsSample(accepts, s)) || null;
}
// The page's own <input type=file accept="..."> - used when the manifest has no `accepts`.
function parseAcceptAttr(a) {
  return (a || '').split(',').map((x) => x.trim().toLowerCase()).filter(Boolean);
}

// ---------- output validation ----------
function magicKind(b) {
  if (!b.length) return null;
  const h = b.subarray(0, 16).toString('latin1');
  const hex = b.subarray(0, 4).toString('hex');
  if (h.startsWith('%PDF-')) return 'pdf';
  if (hex.startsWith('89504e47')) return 'png';
  if (hex.startsWith('ffd8ff')) return 'jpeg';
  if (h.startsWith('RIFF')) return 'riff:' + h.slice(8, 12).trim();
  if (h.startsWith('GIF8')) return 'gif';
  if (h.startsWith('glTF')) return 'glb';
  if (h.slice(4, 8) === 'ftyp') return 'isobmff:' + h.slice(8, 12);
  if (hex === '1a45dfa3') return 'webm/mkv';
  if (h.startsWith('OggS')) return 'ogg';
  if (h.startsWith('fLaC')) return 'flac';
  if (h.startsWith('ID3') || (b[0] === 0xff && (b[1] & 0xe0) === 0xe0)) return 'mp3/aac';
  if (hex === '504b0304') return 'zip';
  if (h.startsWith('BM')) return 'bmp';
  if (hex === '00000100') return 'ico';
  if (h.startsWith('wOF2') || h.startsWith('wOFF') || hex === '00010000' || h.startsWith('OTTO')) return 'font';
  if (h.startsWith('II*') || h.startsWith('MM')) return 'tiff';
  // text-ish outputs (svg, json, csv, srt, dxf, obj, stl, txt)
  const head = b.subarray(0, 512);
  let bin = 0;
  for (const c of head) if (c === 0 || (c < 9)) bin++;
  if (bin === 0) return 'text';
  return null;
}

// ---------- optional QA sign-in (one shared, signed-in context) ----------
const QA_ENV_FILE = process.env.QA_ENV_FILE || '/root/cadtest/.qa_pro';
const ANON = process.env.ANON === '1';
let SHARED_CTX = null;
function readQaEnv() {
  if (ANON || !fs.existsSync(QA_ENV_FILE)) return null;
  const kv = {};
  for (const line of fs.readFileSync(QA_ENV_FILE, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*(QA_EMAIL|QA_PASS)\s*=\s*(.*)$/);
    if (m) kv[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, '');
  }
  return kv.QA_EMAIL && kv.QA_PASS ? { email: kv.QA_EMAIL, pass: kv.QA_PASS } : null;
}
async function newSweepContext(browser) {
  const ctx = await browser.newContext({ acceptDownloads: true });
  await ctx.addInitScript(() => {
    const md = navigator.mediaDevices;
    if (md && md.getUserMedia) {
      const orig = md.getUserMedia.bind(md);
      md.getUserMedia = (...a) => { window.__wantsMedia = true; return orig(...a); };
    }
  });
  return ctx;
}
async function sessionEmail(ctx) {
  const r = await ctx.request.get(BASE + '/api/auth/session');
  const j = await r.json().catch(() => ({}));
  return (j && j.user && j.user.email) || null;
}
// Signs in through the real /auth/sign-in form (credentials provider). Never logs the password.
async function signIn(browser, qa) {
  const ctx = await newSweepContext(browser);
  const page = await ctx.newPage();
  await page.goto(BASE + '/auth/sign-in', { waitUntil: 'domcontentloaded', timeout: 30_000 });
  const form = page.locator('form').filter({ has: page.locator('input[type=password]') }).first();
  await form.locator('input[type=email]').fill(qa.email);
  await form.locator('input[type=password]').fill(qa.pass);
  await form.locator('button[type=submit]').click();
  const until = Date.now() + 30_000;
  let who = null;
  while (Date.now() < until && who !== qa.email) { await page.waitForTimeout(1000); who = await sessionEmail(ctx).catch(() => null); }
  await page.close();
  if (who !== qa.email) { await ctx.close(); throw new Error(`sign-in failed: /api/auth/session shows ${who ? 'a different user' : 'no user'}`); }
  return ctx;
}

// ---------- page run ----------
async function runPage(browser, url) {
  const rec = { url, status: 'OK', reasons: [], pageErrors: [], consoleErrors: [], http: [], red: [], ui: false, sample: null, output: null, ms: 0 };
  const t0 = Date.now();
  const sid = (url.match(/^\/tools\/([^/?#]+)/) || [])[1];
  if (sid && DISABLED.has(sid)) { rec.status = 'SKIPPED'; rec.reasons.push('disabled studio (lib/studios/disabled-ids.json)'); return rec; }
  if (sid && INTERACTIVE.has(sid)) { rec.status = 'SKIPPED'; rec.reasons.push('needs clicks on the canvas (no generic driver)'); return rec; }
  const page = APP_PAGE;
  page.removeAllListeners('pageerror'); page.removeAllListeners('dialog'); page.removeAllListeners('console'); page.removeAllListeners('response');
  page.on('pageerror', (e) => rec.pageErrors.push(String(e.message || e).slice(0, 300)));
  // Playwright dismisses dialogs silently by default; record them (studio-gif hid its error in an alert).
  page.on('dialog', (d) => {
    (rec.dialogs ||= []).push(`${d.type()}: ${d.message().slice(0, 200)}`);
    d.dismiss().catch(() => {});
  });
  page.on('console', (m) => { if (m.type() === 'error') rec.consoleErrors.push(m.text().slice(0, 300)); });
  page.on('response', (r) => {
    try { if (r.status() >= 400 && new URL(r.url()).origin === ORIGIN) rec.http.push(`${r.status()} ${r.url().replace(ORIGIN, '')}`); } catch {}
  });
  let download = null;
  try {
    const resp = await page.goto(BASE + url, { waitUntil: 'domcontentloaded', timeout: 30_000 });
    if (resp && resp.status() >= 400) { rec.status = 'LOAD-ERROR'; rec.reasons.push('document HTTP ' + resp.status()); return rec; }
    // UI rendered? file input, textarea, canvas/video, or an enabled button in <main>.
    const uiSel = 'input[type=file], main textarea, main input[type=text], main canvas, main video, main button, main [contenteditable=true]';
    rec.bridge = await hookBridge(page);
    rec.ui = await page.waitForSelector(uiSel, { state: 'attached', timeout: UI_TIMEOUT }).then(() => true).catch(() => false);
    await page.waitForTimeout(1500);
    rec.red = (await page.locator('.text-red-600:visible, [role=alert]:visible').allInnerTexts().catch(() => [])).map((t) => t.trim()).filter(Boolean).slice(0, 3);
    if (!rec.ui) { rec.status = 'NO-UI'; rec.reasons.push('no file input / main UI within 15s'); return rec; }

    const id = (url.match(/^\/tools\/([^/?#]+)/) || [])[1];
    const accepts = id ? readAccepts(id) : null;
    const hasFileInput = (await page.locator('input[type=file]').count()) > 0;
    const text = (await page.locator('main').innerText().catch(() => '')).slice(0, 4000);
    let sample = pickSample(url, accepts);
    if (!sample && hasFileInput) {
      const attr = parseAcceptAttr(await page.locator('input[type=file]').first().getAttribute('accept').catch(() => ''));
      if (attr.length) { sample = pickSample(url, attr); rec.acceptAttr = attr; }
      else if (!accepts) sample = null;
    }
    if (!hasFileInput || !sample) {
      rec.status = 'SKIPPED';
      rec.reasons.push(!hasFileInput ? (HW_RE.test(text) ? 'needs camera/mic' : 'no file input (text/interactive tool)') : `no sample for accepts=${JSON.stringify(accepts)}`);
      return finish(rec);
    }
    rec.sample = sample.file;
    const multiple = await page.locator('input[type=file]').first().getAttribute('multiple');
    const files = [path.join(SAMPLES, sample.file)];
    const second = SECOND_FILE[sample.file];
    if (multiple !== null && second && fs.existsSync(path.join(SAMPLES, second))) files.push(path.join(SAMPLES, second));
    await appDeliver(page, files);
    await page.waitForTimeout(2000);
    if (sid && PREP[sid]) {
      try { await PREP[sid](page); rec.prep = true; } catch (e) { rec.prepError = String(e.message || e).split('\n')[0].slice(0, 160); }
      await page.waitForTimeout(1000);
    }

    const clicked = new Set();
    const deadline = Date.now() + DL_TIMEOUT;
    while (!download && Date.now() < deadline) {
      const btns = page.locator('button:visible, a[download]:visible, a:visible:has-text("Download")');
      const n = await btns.count();
      let acted = false;
      // Ringtone labels a download "M4R (iPhone)". NOT a bare "MP3": every audio
      // tool has an "MP3" FORMAT chip, and matching it made the sweep pick the
      // format instead of pressing "Apply & Download" — 14 false audio FAILs.
      // Subtitle downloads are labelled ".srt" / ".vtt" / ".txt".
      // Press the tool's action first; a bare Download is used only after an action ran,
      // or when the page has no action at all (auto-processing tools). Otherwise a
      // Download of the ORIGINAL / an unrelated control wins and the tool never runs.
      const override = sid && ACTION_OVERRIDE[sid];
      const isAction = (t) => !!t && t.length <= 40 && (ACTION_RE.test(t) || ACTION_EXTRA_RE.test(t) || (override && override.test(t)))
        && !(NOT_ACTION_RE.test(t) && !/^download/i.test(t));
      const texts = [];
      for (let i = 0; i < n; i++) texts.push((await btns.nth(i).innerText().catch(() => '')).replace(/\s+/g, ' ').trim());
      const pendingAction = texts.some((t) => isAction(t) && !/^download/i.test(t) && !clicked.has(t));
      // Text label first; else an icon-only button named by aria-label/title (TextTool's Download).
      const dlText = page.locator('button:visible, a:visible', { hasText: /^\s*(download|m4r|\.(srt|vtt|txt)\b)/i }).first();
      const dlIcon = page.locator('button:visible[aria-label^="Download" i], button:visible[title^="Download" i]').first();
      const dlFirst = (await dlText.count()) ? dlText : dlIcon;
      if ((clicked.size > 0 || !pendingAction) && await dlFirst.count() && !(await dlFirst.isDisabled().catch(() => true))) {
        clicked.add('Download'); await dlFirst.click({ timeout: 3000 }).catch(() => {}); acted = true;
      }
      // Override label first (it is the tool's real action), then the generic ones.
      const order = [...Array(n).keys()].sort((a, b) => Number(!!(override && override.test(texts[b]))) - Number(!!(override && override.test(texts[a]))));
      for (const i of order) {
        if (acted) break;
        const b = btns.nth(i);
        const t = texts[i];
        if (!isAction(t)) continue;
        if (await b.isDisabled().catch(() => true)) continue;
        const isDl = /^download/i.test(t);
        if (!isDl && clicked.has(t)) continue; // press each action once; re-press Download
        clicked.add(t);
        await b.click({ timeout: 3000 }).catch(() => {});
        acted = true;
      }
      await page.waitForTimeout(acted ? 1500 : 750);
      download = download || await appSaved(page);
      // The daily free-export quota is enforced per visitor server-side; a fresh context does not reset it.
      if (await page.getByText(/free limit reached/i).first().isVisible().catch(() => false)) { rec.quota = true; break; }
      const red = (await page.locator('.text-red-600:visible, [role=alert]:visible').allInnerTexts().catch(() => [])).map((x) => x.trim()).filter((x) => x && RED_ERR_RE.test(x)); // red styling alone (an invoice 'Discount' line) is not an error
      if (red.length && !download) { rec.red = red.slice(0, 3); break; }
      const badDialog = (rec.dialogs || []).find((m) => DIALOG_FAIL_RE.test(m));
      if (badDialog && !download) { rec.dialogFail = badDialog; break; }
    }
    rec.clicked = [...clicked];
    if (!download && rec.quota) { rec.status = 'SKIPPED'; rec.reasons.push('daily free-export limit reached (quota modal) - output not testable today'); return finish(rec); }
    if (!download) {
      const wantsMedia = await page.evaluate(() => !!window.__wantsMedia).catch(() => false);
      if (wantsMedia || (!clicked.size && HW_RE.test(text))) { rec.status = 'SKIPPED'; rec.reasons.push('needs camera/mic'); return finish(rec); }
      if (!clicked.size) {
        rec.buttons = (await page.locator('main button:visible').allInnerTexts().catch(() => [])).map((t) => t.replace(/\s+/g, ' ').trim()).filter((t) => t && t.length <= 40);
        rec.status = 'SKIPPED'; rec.reasons.push('uploaded, but no recognisable action/download button'); return finish(rec);
      }
      rec.status = 'UPLOAD-FAIL';
      rec.reasons.push(rec.red.length ? 'error shown: ' + rec.red[0].slice(0, 160)
        : rec.dialogFail ? 'error dialog: ' + rec.dialogFail
        : (rec.dialogs || []).length ? `no download within ${DL_TIMEOUT / 1000}s (dialog: ${rec.dialogs[0]})`
        : `no download within ${DL_TIMEOUT / 1000}s`);
      return finish(rec);
    }
    const out = path.join(DL_DIR, url.replace(/\W+/g, '_') + '-' + download.suggestedFilename());
    fs.writeFileSync(out, download.buf);
    const b = download.buf;
    closeSheet();
    const kind = magicKind(b);
    rec.output = { name: download.suggestedFilename(), bytes: b.length, magic: b.subarray(0, 8).toString('hex'), kind };
    if (!b.length) { rec.status = 'UPLOAD-FAIL'; rec.reasons.push('empty download'); }
    else if (!kind) { rec.status = 'UPLOAD-FAIL'; rec.reasons.push('unrecognised output magic ' + rec.output.magic); }
    else rec.status = 'UPLOAD-OK';
    return finish(rec);
  } catch (e) {
    rec.status = 'LOAD-ERROR';
    rec.reasons.push(String(e.message || e).split('\n')[0].slice(0, 200));
    return rec;
  } finally {
    rec.ms = Date.now() - t0;
    // one WebView: close any native Save/Share sheet a skipped/failed page left open
    if (!download) { const late = await appSaved(page); if (late) closeSheet(); }
  }
}
// A page that "works" but threw is still reported, as OK-with-errors -> LOAD-ERROR only when it has a pageerror.
function finish(rec) {
  if ((rec.status === 'OK' || rec.status === 'SKIPPED') && rec.pageErrors.length) {
    rec.reasons.unshift('pageerror: ' + rec.pageErrors[0].slice(0, 160));
    rec.status = 'LOAD-ERROR';
  }
  return rec;
}

// ---------- URL list ----------
async function urlList() {
  const xml = await (await fetch(BASE + '/sitemap.xml')).text();
  let locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim());
  // follow a sitemap index one level
  const nested = locs.filter((l) => /\.xml(\?|$)/.test(l));
  for (const n of nested) {
    const x = await (await fetch(n.replace(/^https?:\/\/[^/]+/, BASE))).text().catch(() => '');
    locs.push(...[...x.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim()));
  }
  const paths = [...new Set(locs.map((l) => { try { return new URL(l).pathname.replace(/\/$/, ''); } catch { return ''; } }))];
  const tools = paths.filter((p) => /^\/tools\/[^/]+$/.test(p));
  const pairs = paths.filter((p) => /^\/convert\/[^/]+-to-[^/]+$/.test(p));
  return [...tools, ...pairs].filter((p) => !ONLY || ONLY.test(p));
}

// ---------- main ----------
const urls = await urlList();
console.error(`sweeping ${urls.length} pages against ${BASE} (concurrency ${CONCURRENCY})`);
const browser = await chromium.connectOverCDP(APP_CDP);
APP_PAGE = browser.contexts()[0].pages().find((p) => /xonvert\.com/.test(p.url())) || browser.contexts()[0].pages()[0];
console.error('attached to app WebView at ' + APP_PAGE.url());
const qa = readQaEnv();
if (qa) {
  await APP_PAGE.goto(BASE + '/auth/sign-in', { waitUntil: 'domcontentloaded', timeout: 30_000 });
  const form = APP_PAGE.locator('form').filter({ has: APP_PAGE.locator('input[type=password]') }).first();
  await form.locator('input[type=email]').fill(qa.email);
  await form.locator('input[type=password]').fill(qa.pass);
  await form.locator('button[type=submit]').click();
  let who = null; const until = Date.now() + 30_000;
  while (Date.now() < until && who !== qa.email) {
    await APP_PAGE.waitForTimeout(1000);
    who = await APP_PAGE.evaluate(() => fetch('/api/auth/session').then((r) => r.json()).then((j) => j && j.user && j.user.email).catch(() => null));
  }
  console.error(who === qa.email ? `signed in inside the app as ${qa.email}` : 'SIGN-IN FAILED inside the app (quota may hit)');
}
const results = [];
let next = 0;
let hung = false;
async function worker() {
  while (next < urls.length) {
    const u = urls[next++];
    // A crashed WebView renderer makes CDP calls hang: cap each page, and on a hang
    // save what we have and exit 3 so the runner can restart the app and resume.
    const r = await Promise.race([runPage(browser, u), new Promise((res) => setTimeout(() => res(null), 150_000))]);
    if (!r) { console.log(`HUNG        ${u} - page did not finish in 150s (WebView renderer likely crashed)`); results.push({ url: u, status: 'HUNG', reasons: ['hung'], pageErrors: [], http: [], red: [] }); hung = true; break; }
    results.push(r);
    const why = r.reasons[0] ? ' - ' + r.reasons[0] : '';
    const out = r.output ? ` ${r.output.kind} ${r.output.bytes}B` : '';
    console.log(`${r.status.padEnd(11)} ${u}${out}${why}`);
  }
}
await Promise.all(Array.from({ length: CONCURRENCY }, worker));
if (hung) console.error('stopping after a hung page: restart the app and resume with ONLY=<remaining>');
let endSession = null;
await browser.close().catch(() => {});

results.sort((a, b) => a.url.localeCompare(b.url));
const counts = {};
for (const r of results) counts[r.status] = (counts[r.status] || 0) + 1;
// root-cause signatures: first pageerror, else first same-origin 4xx/5xx, else first reason
const sig = (r) => (r.pageErrors[0] ? 'pageerror: ' + r.pageErrors[0].replace(/\d+/g, 'N').slice(0, 120)
  : r.http[0] ? 'http: ' + r.http[0].replace(/\?.*$/, '')
  : r.red[0] ? 'red: ' + r.red[0].slice(0, 120) : r.reasons[0] || '?');
const groups = {};
for (const r of results) if (['LOAD-ERROR', 'NO-UI', 'UPLOAD-FAIL'].includes(r.status)) (groups[sig(r)] ||= []).push(r.url);
fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
fs.writeFileSync(OUT_JSON, JSON.stringify({ base: BASE, at: new Date().toISOString(), counts, signatures: groups, results }, null, 2));

console.log('\n==== summary ====');
for (const [k, v] of Object.entries(counts)) console.log(`${k.padEnd(12)} ${v}`);
console.log('\n==== failure signatures (count, pages) ====');
for (const [s, list] of Object.entries(groups).sort((a, b) => b[1].length - a[1].length)) {
  console.log(`${String(list.length).padStart(3)}  ${s}`);
  console.log('       ' + list.slice(0, 8).join(' ') + (list.length > 8 ? ` ... +${list.length - 8}` : ''));
}
console.log(`\nreport: ${OUT_JSON}   downloads: ${DL_DIR}`);
process.exit(Object.keys(groups).length ? 1 : 0);
