"""Derive scripts/live_sweep_app.mjs from scripts/live_sweep.mjs: the same sweep, but run INSIDE the
Xonvert Android app's WebView on a real phone (CDP), feeding files through the app bridge and reading
results from the bridge's saveFile messages. Every replacement must match exactly once."""
import sys

src_path, out_path = sys.argv[1], sys.argv[2]
s = open(src_path, encoding='utf-8', newline='').read()


def rep(old, new, count=1):
    global s
    n = s.count(old)
    if n != count:
        raise SystemExit(f'expected {count} match(es), found {n}: {old[:80]!r}')
    s = s.replace(old, new)


rep(" * Live breakage sweep: visits EVERY", " * APP VARIANT (generated by mk_app_sweep.py from live_sweep.mjs — edit that, not this):\n"
    " * runs inside the Xonvert Android app's WebView over CDP (env APP_CDP, e.g. http://127.0.0.1:9471),\n"
    " * files go in through window.__xonvertAppEvent (the share-in path) and results come out as the\n"
    " * app bridge's saveFile messages; each native Save/Share sheet is closed with adb BACK.\n *\n * Live breakage sweep: visits EVERY")
rep("const CONCURRENCY = Number(process.env.CONCURRENCY || 2);", "const CONCURRENCY = 1; // one WebView\nconst APP_CDP = process.env.APP_CDP || 'http://127.0.0.1:9471';\n"
    "const ADB = process.env.ADB || '/mnt/c/science/android-sdk/platform-tools/adb.exe';\nlet APP_PAGE = null;")
rep("import { fileURLToPath } from 'node:url';", """import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

// ---- app bridge helpers ----
const hookBridge = (page) => page.evaluate(() => {
  if (window.__xvHooked || !window.XonvertBridge) return !!window.XonvertBridge;
  // On Android XonvertBridge is a Java-bound object: assigning over its method is silently
  // ignored, so replace the whole object with a recording proxy.
  const real = window.XonvertBridge;
  window.__msgs = [];
  const proxy = { postMessage: (m) => { window.__msgs.push(m); return real.postMessage(m); } };
  try { window.XonvertBridge = proxy; } catch (e) { return 'readonly'; }
  window.__xvHooked = true;
  return window.XonvertBridge === proxy ? true : 'not-replaced';
}).catch(() => false);
const appDeliver = async (page, files) => {
  const payload = files.map((f) => ({ name: path.basename(f), mime: mimeOf(f), data: fs.readFileSync(f).toString('base64') }));
  await page.evaluate((fl) => window.__xonvertAppEvent && window.__xonvertAppEvent({ type: 'files', files: fl }), payload);
};
const mimeOf = (f) => ({ png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif', heic: 'image/heic',
  svg: 'image/svg+xml', pdf: 'application/pdf', wav: 'audio/wav', mp3: 'audio/mpeg', mp4: 'video/mp4', mov: 'video/quicktime',
  mkv: 'video/x-matroska', avi: 'video/x-msvideo', txt: 'text/plain', csv: 'text/csv', json: 'application/json', md: 'text/markdown',
  srt: 'application/x-subrip', vtt: 'text/vtt', zip: 'application/zip', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  epub: 'application/epub+zip', ttf: 'font/ttf', otf: 'font/otf' })[path.extname(f).slice(1).toLowerCase()] || 'application/octet-stream';
const appSaved = async (page) => {
  const m = await page.evaluate(() => {
    for (const raw of window.__msgs || []) { try { const x = JSON.parse(raw); if (x.type === 'saveFile') return { name: x.name, data: x.data }; } catch {} }
    return null;
  }).catch(() => null);
  if (!m) return null;
  const buf = Buffer.from(m.data, 'base64');
  return { buf, suggestedFilename: () => m.name };
};
const closeSheet = () => { try { execFileSync(ADB, ['shell', 'input', 'keyevent', 'KEYCODE_BACK'], { timeout: 8000 }); } catch {} };""")

rep("""  const ctx = SHARED_CTX || await newSweepContext(browser);
  const page = await ctx.newPage();""", """  const page = APP_PAGE;
  page.removeAllListeners('pageerror'); page.removeAllListeners('dialog'); page.removeAllListeners('console'); page.removeAllListeners('response');""")
rep("""  let download = null;
  page.on('download', (d) => { download = d; });""", """  let download = null;""")
rep("""    if (!resp || resp.status() >= 400) { rec.status = 'LOAD-ERROR'; rec.reasons.push('document HTTP ' + (resp ? resp.status() : 'none')); return rec; }""",
    """    if (resp && resp.status() >= 400) { rec.status = 'LOAD-ERROR'; rec.reasons.push('document HTTP ' + resp.status()); return rec; }""")
rep("""    rec.ui = await page.waitForSelector(uiSel""", """    rec.bridge = await hookBridge(page);
    rec.ui = await page.waitForSelector(uiSel""")
rep("""    await page.locator('input[type=file]').first().setInputFiles(files);""", """    await appDeliver(page, files);""")
rep("""      await page.waitForTimeout(acted ? 1500 : 750);""", """      await page.waitForTimeout(acted ? 1500 : 750);
      download = download || await appSaved(page);""")
rep("""    const out = path.join(DL_DIR, url.replace(/\\W+/g, '_') + '-' + download.suggestedFilename());
    await download.saveAs(out);
    const b = fs.readFileSync(out);""", """    const out = path.join(DL_DIR, url.replace(/\\W+/g, '_') + '-' + download.suggestedFilename());
    fs.writeFileSync(out, download.buf);
    const b = download.buf;
    closeSheet();""")
rep("""    if (SHARED_CTX) await page.close().catch(() => {});
    else await ctx.close().catch(() => {});""", """    // one WebView: close any native Save/Share sheet a skipped/failed page left open
    if (!download) { const late = await appSaved(page); if (late) closeSheet(); }""")
rep("""    const r = await runPage(browser, u);""", """    // A crashed WebView renderer makes CDP calls hang: cap each page, and on a hang
    // save what we have and exit 3 so the runner can restart the app and resume.
    const r = await Promise.race([runPage(browser, u), new Promise((res) => setTimeout(() => res(null), 150_000))]);
    if (!r) { console.log(`HUNG        ${u} - page did not finish in 150s (WebView renderer likely crashed)`); results.push({ url: u, status: 'HUNG', reasons: ['hung'], pageErrors: [], http: [], red: [] }); hung = true; break; }""")
rep("""let next = 0;""", """let next = 0;
let hung = false;""")
rep("""await Promise.all(Array.from({ length: CONCURRENCY }, worker));""", """await Promise.all(Array.from({ length: CONCURRENCY }, worker));
if (hung) console.error('stopping after a hung page: restart the app and resume with ONLY=<remaining>');""")
rep("""const browser = await chromium.launch({ executablePath: CHROME, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream',
  // video-mute & co. record by real-time playback; headless blocks unmuted autoplay without this.
  '--autoplay-policy=no-user-gesture-required'] });
const qa = readQaEnv();
if (qa) {
  SHARED_CTX = await signIn(browser, qa);
  console.error(`signed in as ${qa.email} (session confirmed via /api/auth/session); all pages share this context`);
} else console.error(ANON ? 'ANON=1: anonymous contexts' : `no ${QA_ENV_FILE}: anonymous contexts`);""", """const browser = await chromium.connectOverCDP(APP_CDP);
APP_PAGE = browser.contexts()[0].pages().find((p) => /xonvert\\.com/.test(p.url())) || browser.contexts()[0].pages()[0];
console.error('attached to app WebView at ' + APP_PAGE.url());
const qa = readQaEnv();
if (qa) {
  await APP_PAGE.goto(BASE + '/auth/sign-in', { waitUntil: 'domcontentloaded', timeout: 30_000 });
  const form = APP_PAGE.locator('form').filter({ has: APP_PAGE.locator('input[type=password]') }).first();
  await form.locator('input[type=email]').fill(qa.email);
  await form.locator('input[type=password]').fill(qa.pass);
  await form.locator('button[type=submit]').click();
  let who = null; const until = Date.now() + 30_000;
  while (Date.now() < until && who !== qa.email) {
    await APP_PAGE.waitForTimeout(1000);
    who = await APP_PAGE.evaluate(() => fetch('/api/auth/session').then((r) => r.json()).then((j) => j && j.user && j.user.email).catch(() => null));
  }
  console.error(who === qa.email ? `signed in inside the app as ${qa.email}` : 'SIGN-IN FAILED inside the app (quota may hit)');
}""")
rep("""if (SHARED_CTX) { endSession = await sessionEmail(SHARED_CTX).catch(() => null); console.error(`session at end: ${endSession === qa.email ? 'still signed in' : 'LOST (' + endSession + ')'}`); }
await browser.close();""", """await browser.close().catch(() => {});""")
open(out_path, 'w', encoding='utf-8', newline='').write(s)
print('wrote', out_path, len(s))
