/**
 * People-also-ask — assembles a "related questions" list from local memory
 * clusters. Pure on-device — no aggregated server data.
 *
 *   suggest(query, opts) → [{ question, score }]
 *
 * The list is generated by token overlap against memory and a small
 * curated template set per query class (compress → ["how to convert",
 * "how to merge", "how to split"]).
 *
 * Exposes window.oioxoPaa = { suggest, templates }.
 */
(function(){
  'use strict';
  if (typeof window === 'undefined') return;
  if (window.oioxoPaa) return;

  // Curated templates by trigger verb / topic.
  const TEMPLATES = {
    compress:  ['convert {x}', 'merge {x}', 'split {x}', 'rotate {x}', 'how to compress {x}'],
    convert:   ['compress after convert', 'convert online', 'convert in browser'],
    merge:     ['split {x}', 'compress {x}', 'extract pages from {x}'],
    split:     ['merge {x}', 'extract pages from {x}'],
    image:     ['resize image', 'remove background', 'compress image', 'crop image'],
    pdf:       ['compress pdf', 'merge pdf', 'split pdf', 'extract text from pdf'],
    mp4:       ['compress mp4', 'convert mp4 to avi', 'extract audio from mp4'],
    weather:   ['weather forecast', 'weather in london', 'climate'],
    time:      ['world clock', 'time zones', 'utc time'],
    price:     ['btc price', 'usd to eur'],
  };

  function tokens(s){
    return String(s || '').toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').split(/\s+/).filter(Boolean);
  }

  function fromMemory(query, opts){
    const limit = (opts && opts.limit) || 4;
    if (!window.oioxoMemory || !window.oioxoMemory.recent) return [];
    const recents = window.oioxoMemory.recent(50);
    const qTokens = tokens(query);
    if (!qTokens.length) return [];
    const seen = new Set([query.toLowerCase().trim()]);
    const scored = [];
    for (const r of recents){
      if (!r || !r.query) continue;
      const lc = r.query.toLowerCase().trim();
      if (seen.has(lc)) continue;
      seen.add(lc);
      const tt = tokens(lc);
      const overlap = tt.filter((t) => qTokens.includes(t)).length;
      if (overlap === 0) continue;
      const score = overlap / Math.max(qTokens.length, tt.length);
      if (score < 0.2) continue;
      scored.push({ question: r.query, score });
    }
    return scored.sort((a, b) => b.score - a.score).slice(0, limit);
  }

  function fromTemplates(query, opts){
    const limit = (opts && opts.limit) || 4;
    const qTokens = tokens(query);
    const out = [];
    for (const trigger of Object.keys(TEMPLATES)){
      if (qTokens.includes(trigger)){
        const subject = qTokens.find((t) => t !== trigger) || '';
        for (const tpl of TEMPLATES[trigger]){
          const q = tpl.replace('{x}', subject).trim();
          if (q && q !== query) out.push({ question: q, score: 0.4 });
          if (out.length >= limit * 2) break;
        }
      }
      if (out.length >= limit * 2) break;
    }
    return out;
  }

  function suggest(query, opts){
    opts = opts || {};
    const limit = opts.limit || 4;
    const a = fromMemory(query, opts);
    if (a.length >= limit) return a.slice(0, limit);
    const b = fromTemplates(query, opts);
    const merged = a.slice();
    for (const x of b){
      if (!merged.some((y) => y.question === x.question)){
        merged.push(x);
        if (merged.length >= limit) break;
      }
    }
    return merged.sort((a, b) => b.score - a.score).slice(0, limit);
  }

  window.oioxoPaa = { suggest, templates: TEMPLATES };
})();
