/**
 * Format encyclopedia profiles for everyday formats (CAD & 3D live in
 * lib/convert/cad3d.ts). Hand-written and factual — add a format only with a
 * real profile and at least one working tool; never generate these.
 */
export interface FormatProfile { name: string; what: string; usedBy: string; tools: string[] }

export const FORMAT_PROFILES: Record<string, FormatProfile> = {
  png: { name: 'PNG (Portable Network Graphics)', what: 'PNG is a lossless image format with full transparency support. It keeps every pixel exactly, which makes it ideal for screenshots, logos and graphics — and large for photos.', usedBy: 'Screenshots on every OS, web graphics, design tools such as Figma and Photoshop.', tools: ['image-convert-format', 'image-compress', 'image-resize', 'image-ocr'] },
  jpg: { name: 'JPG / JPEG', what: 'JPEG is the standard lossy photo format since 1992. It makes photos small by discarding detail the eye barely notices, but it has no transparency and blurs sharp text at low quality.', usedBy: 'Digital cameras, phones, email, social media and nearly every website.', tools: ['image-convert-format', 'image-compress', 'image-resize', 'images-to-pdf'] },
  webp: { name: 'WebP', what: 'WebP is Google’s image format for the web, supporting lossy and lossless compression, transparency and animation. It is usually much smaller than JPG or PNG at the same quality.', usedBy: 'Websites and CDNs; every modern browser displays it.', tools: ['image-convert-format', 'image-compress'] },
  avif: { name: 'AVIF', what: 'AVIF is a newer image format based on the AV1 video codec. It is typically smaller than WebP at the same visible quality, but slower to encode.', usedBy: 'Modern websites and image CDNs; supported in current Chrome, Firefox and Safari.', tools: ['image-convert-format', 'image-compress'] },
  heic: { name: 'HEIC / HEIF', what: 'HEIC is the photo format iPhones use by default. It stores photos at roughly half the size of JPG, but many Windows programs, websites and upload forms cannot open it.', usedBy: 'iPhone and iPad cameras (iOS 11+), macOS Photos.', tools: ['image-heic-convert'] },
  gif: { name: 'GIF', what: 'GIF is a 1987 image format limited to 256 colours that supports simple animation. It compresses poorly, so animated GIFs are often very large for their length.', usedBy: 'Reactions in chats, animations in docs and READMEs, old web graphics.', tools: ['video-to-gif', 'video-gif-to-video', 'image-convert-format'] },
  svg: { name: 'SVG (Scalable Vector Graphics)', what: 'SVG describes images as shapes and paths in XML, so it stays sharp at any size. Many apps, documents and social sites cannot display it and need a PNG instead.', usedBy: 'Logos and icons on the web, design tools such as Figma, Illustrator and Inkscape.', tools: [] },
  mp4: { name: 'MP4 (MPEG-4 Part 14)', what: 'MP4 is the most widely supported video container, usually holding H.264 video and AAC audio. It plays on virtually every phone, browser, TV and editor.', usedBy: 'Phones, YouTube and social media, streaming, video editors.', tools: ['video-compress', 'video-convert-format', 'video-extract-audio', 'video-to-gif'] },
  mov: { name: 'MOV (QuickTime)', what: 'MOV is Apple’s QuickTime container. iPhones record MOV, often with HEVC video, which many Windows PCs, Android phones and websites cannot play.', usedBy: 'iPhone and Mac video recording, Final Cut Pro.', tools: ['video-convert-format', 'video-compress', 'video-extract-audio'] },
  mkv: { name: 'MKV (Matroska)', what: 'MKV is an open container that can hold several video, audio and subtitle tracks. It plays in VLC but often not on phones, TVs, editors or social sites.', usedBy: 'Downloaded films and series, screen recorders such as OBS.', tools: ['video-convert-format', 'video-compress'] },
  avi: { name: 'AVI (Audio Video Interleave)', what: 'AVI is Microsoft’s 1992 video container. Old camcorder and archive videos use it, usually with dated codecs that modern browsers and phones cannot play.', usedBy: 'Old camcorders, Windows Movie Maker, video archives.', tools: ['video-convert-format', 'video-compress'] },
  webm: { name: 'WebM', what: 'WebM is an open web video format using VP8/VP9 or AV1 video and Opus or Vorbis audio. Chrome, Firefox and Edge play it natively.', usedBy: 'HTML5 video on websites, browser screen recordings.', tools: ['video-convert-format'] },
  mp3: { name: 'MP3', what: 'MP3 is the universal compressed audio format. At 192 kbps it sounds transparent to most listeners at about a tenth of the size of uncompressed audio.', usedBy: 'Music players, podcasts, phones, car stereos.', tools: ['audio-convert-format', 'audio-trim', 'audio-volume', 'audio-to-text'] },
  wav: { name: 'WAV', what: 'WAV stores uncompressed audio — about 10 MB per stereo minute. It is the standard for recording and editing because nothing is lost.', usedBy: 'Audio editors and DAWs, recorders, samplers.', tools: ['audio-convert-format', 'audio-trim', 'audio-volume', 'audio-normalize'] },
  pdf: { name: 'PDF (Portable Document Format)', what: 'PDF preserves a document’s exact layout on any device. Pages can contain real text, images, or — in scans — only pictures of text.', usedBy: 'Contracts, invoices, forms, reports, e-books and scanned documents.', tools: ['pdf-compress', 'pdf-merge', 'pdf-split', 'pdf-to-images', 'pdf-to-text', 'pdf-ocr'] },
  docx: { name: 'DOCX (Word document)', what: 'DOCX is Microsoft Word’s document format — a ZIP of XML files describing text, styles, tables and images.', usedBy: 'Microsoft Word, Google Docs, LibreOffice.', tools: ['doc-convert'] },
  epub: { name: 'EPUB', what: 'EPUB is the open e-book format: reflowable HTML chapters packed in a ZIP, so text adapts to any screen size.', usedBy: 'Apple Books, Kobo, Google Play Books and most e-readers (not older Kindles).', tools: ['ebook-convert'] },
  srt: { name: 'SRT (SubRip subtitles)', what: 'SRT is the simplest and most widely supported subtitle format: numbered cues with start and end times and plain text.', usedBy: 'Video players (VLC, YouTube uploads), video editors.', tools: ['subtitle-cleaner', 'subtitle-generate', 'subtitle-timing-shifter'] },
  vtt: { name: 'VTT (WebVTT)', what: 'WebVTT is the web’s subtitle format for HTML5 video. It is close to SRT but adds a header and styling options.', usedBy: 'HTML5 video players, YouTube, streaming sites.', tools: ['subtitle-cleaner', 'subtitle-timing-shifter'] },
  ttf: { name: 'TTF (TrueType font)', what: 'TrueType is the font format Apple and Microsoft introduced in 1991, still installed on every operating system.', usedBy: 'Windows, macOS, Linux, and most apps and websites.', tools: ['font-convert'] },
  otf: { name: 'OTF (OpenType font)', what: 'OpenType extends TrueType with advanced typography — ligatures, alternates and larger character sets — in a single cross-platform file.', usedBy: 'Professional typefaces, design tools such as Adobe apps and Figma.', tools: ['font-convert'] },
};
