/**
 * oioxo Code — the SEEDED VERIFIED LIBRARY (cold-start fix for the "any device"
 * corpus). Semantic retrieval (embed.ts) is the catalog; this stocks the shelves
 * so a weak device hits a proven block for most common asks BEFORE the network
 * grows. Every brick here is oracle-VALIDATED at build (buildBrickSeed type-checks
 * each), so the corpus is correct by construction. Broad, small, richly-tagged
 * units across string/array/number/object/async/date/validation/dom/storage/
 * data-structures/game/color/net — the common coding surface.
 */
import { type Brick, makeBrick } from './bricks';

const lib = (b: Omit<Brick, 'id' | 'ts' | 'origin' | 'verified'>): Brick => makeBrick({ ...b, origin: 'seed', verified: true });

export const LIBRARY_BRICKS: Brick[] = [
  // ── string ──────────────────────────────────────────────────────────────
  lib({ title: 'capitalize — uppercase the first letter of a string', kind: 'string', lang: 'ts', tags: ['capitalize', 'uppercase', 'first', 'letter', 'string', 'case'], use: 'capitalize("hi")', code: `export const capitalize = (s: string): string => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s);\n` }),
  lib({ title: 'titleCase — capitalize every word', kind: 'string', lang: 'ts', tags: ['title', 'case', 'words', 'capitalize', 'string'], use: 'titleCase("hello world")', code: `export const titleCase = (s: string): string => s.replace(/\\w\\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());\n` }),
  lib({ title: 'truncate — shorten a string with an ellipsis', kind: 'string', lang: 'ts', tags: ['truncate', 'shorten', 'ellipsis', 'clip', 'cut', 'string', 'length'], use: 'truncate(text, 80)', code: `export function truncate(s: string, max: number): string {\n  return s.length > max ? s.slice(0, max - 1).trimEnd() + '…' : s;\n}\n` }),
  lib({ title: 'escapeHtml — make text safe to put in HTML', kind: 'string', lang: 'ts', tags: ['escape', 'html', 'sanitize', 'safe', 'xss', 'entities', 'string'], use: 'el.innerHTML = escapeHtml(userText)', code: `export function escapeHtml(s: string): string {\n  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));\n}\n` }),
  lib({ title: 'slugify — make a URL-safe slug from text', kind: 'string', lang: 'ts', tags: ['slug', 'slugify', 'url', 'permalink', 'seo', 'kebab', 'string'], use: 'slugify("My Post!") → "my-post"', code: `export function slugify(s: string): string {\n  return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');\n}\n` }),
  lib({ title: 'randomId — short random alphanumeric id', kind: 'string', lang: 'ts', tags: ['random', 'id', 'uuid', 'token', 'unique', 'key', 'generate'], use: 'const id = randomId()', code: `export function randomId(len = 8): string {\n  const c = 'abcdefghijklmnopqrstuvwxyz0123456789';\n  let out = '';\n  for (let i = 0; i < len; i++) out += c[Math.floor(Math.random() * c.length)];\n  return out;\n}\n` }),
  lib({ title: 'wordCount — count words in a string', kind: 'string', lang: 'ts', tags: ['word', 'count', 'words', 'text', 'tokens', 'split'], use: 'wordCount(text)', code: `export const wordCount = (s: string): number => (s.trim().match(/\\S+/g) || []).length;\n` }),

  // ── array ───────────────────────────────────────────────────────────────
  lib({ title: 'chunk — split an array into groups of n', kind: 'array', lang: 'ts', tags: ['chunk', 'split', 'group', 'batch', 'array', 'partition', 'pages'], use: 'chunk([1,2,3,4], 2)', code: `export function chunk<T>(xs: T[], n: number): T[][] {\n  const out: T[][] = [];\n  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n));\n  return out;\n}\n` }),
  lib({ title: 'unique — remove duplicates from an array', kind: 'array', lang: 'ts', tags: ['unique', 'dedupe', 'distinct', 'duplicates', 'set', 'array'], use: 'unique([1,1,2])', code: `export const unique = <T>(xs: T[]): T[] => Array.from(new Set(xs));\n` }),
  lib({ title: 'range — array of numbers from start to end', kind: 'array', lang: 'ts', tags: ['range', 'sequence', 'numbers', 'list', 'array', 'iota'], use: 'range(0, 5) → [0,1,2,3,4]', code: `export function range(start: number, end: number, step = 1): number[] {\n  const out: number[] = [];\n  for (let i = start; i < end; i += step) out.push(i);\n  return out;\n}\n` }),
  lib({ title: 'shuffle — randomize an array (Fisher–Yates)', kind: 'array', lang: 'ts', tags: ['shuffle', 'random', 'randomize', 'array', 'mix', 'order'], use: 'shuffle(deck)', code: `export function shuffle<T>(xs: T[]): T[] {\n  const a = [...xs];\n  for (let i = a.length - 1; i > 0; i--) {\n    const j = Math.floor(Math.random() * (i + 1));\n    [a[i], a[j]] = [a[j], a[i]];\n  }\n  return a;\n}\n` }),
  lib({ title: 'sortBy — sort an array by a key function', kind: 'array', lang: 'ts', tags: ['sort', 'order', 'sortby', 'key', 'array', 'compare'], use: 'sortBy(users, (u) => u.age)', code: `export function sortBy<T>(xs: T[], key: (x: T) => number | string): T[] {\n  return [...xs].sort((a, b) => (key(a) > key(b) ? 1 : key(a) < key(b) ? -1 : 0));\n}\n` }),
  lib({ title: 'partition — split an array by a predicate', kind: 'array', lang: 'ts', tags: ['partition', 'split', 'filter', 'group', 'predicate', 'array'], use: 'const [pass, fail] = partition(xs, ok)', code: `export function partition<T>(xs: T[], pred: (x: T) => boolean): [T[], T[]] {\n  const yes: T[] = [], no: T[] = [];\n  for (const x of xs) (pred(x) ? yes : no).push(x);\n  return [yes, no];\n}\n` }),
  lib({ title: 'sum + average of a number array', kind: 'array', lang: 'ts', tags: ['sum', 'average', 'mean', 'total', 'numbers', 'array', 'add'], use: 'sum([1,2,3]); average([1,2,3])', code: `export const sum = (xs: number[]): number => xs.reduce((a, b) => a + b, 0);\nexport const average = (xs: number[]): number => (xs.length ? sum(xs) / xs.length : 0);\n` }),

  // ── number / math ─────────────────────────────────────────────────────────
  lib({ title: 'lerp — linear interpolate between two numbers', kind: 'math', lang: 'ts', tags: ['lerp', 'interpolate', 'blend', 'mix', 'tween', 'animate', 'number'], use: 'lerp(0, 100, 0.5) → 50', code: `export const lerp = (a: number, b: number, t: number): number => a + (b - a) * t;\n` }),
  lib({ title: 'roundTo — round to a number of decimals', kind: 'math', lang: 'ts', tags: ['round', 'decimals', 'precision', 'fixed', 'number', 'money'], use: 'roundTo(3.14159, 2) → 3.14', code: `export const roundTo = (n: number, dp = 0): number => Math.round(n * 10 ** dp) / 10 ** dp;\n` }),
  lib({ title: 'randomInt — random integer in a range', kind: 'math', lang: 'ts', tags: ['random', 'integer', 'int', 'dice', 'number', 'range', 'rand'], use: 'randomInt(1, 6)', code: `export const randomInt = (min: number, max: number): number => Math.floor(Math.random() * (max - min + 1)) + min;\n` }),
  lib({ title: 'formatBytes — human-readable file size', kind: 'format', lang: 'ts', tags: ['bytes', 'filesize', 'size', 'human', 'kb', 'mb', 'format'], use: 'formatBytes(1536) → "1.5 KB"', code: `export function formatBytes(n: number): string {\n  if (n < 1024) return n + ' B';\n  const u = ['KB', 'MB', 'GB', 'TB'];\n  let i = -1;\n  do { n /= 1024; i++; } while (n >= 1024 && i < u.length - 1);\n  return n.toFixed(1) + ' ' + u[i];\n}\n` }),
  lib({ title: 'formatCurrency — format a number as money', kind: 'format', lang: 'ts', tags: ['currency', 'money', 'price', 'dollars', 'format', 'number', 'intl'], use: 'formatCurrency(19.9) → "$19.90"', code: `export const formatCurrency = (n: number, currency = 'USD'): string =>\n  new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(n);\n` }),

  // ── object ──────────────────────────────────────────────────────────────
  lib({ title: 'pick — keep only some keys of an object', kind: 'object', lang: 'ts', tags: ['pick', 'select', 'keys', 'object', 'subset', 'filter'], use: 'pick(user, ["id", "name"])', code: `export function pick<T extends object, K extends keyof T>(obj: T, keys: K[]): Pick<T, K> {\n  const out = {} as Pick<T, K>;\n  for (const k of keys) if (k in obj) out[k] = obj[k];\n  return out;\n}\n` }),
  lib({ title: 'omit — remove some keys from an object', kind: 'object', lang: 'ts', tags: ['omit', 'remove', 'exclude', 'keys', 'object', 'without'], use: 'omit(user, ["password"])', code: `export function omit<T extends object, K extends keyof T>(obj: T, keys: K[]): Omit<T, K> {\n  const out = { ...obj };\n  for (const k of keys) delete out[k];\n  return out;\n}\n` }),
  lib({ title: 'deepClone — copy a plain object/array deeply', kind: 'object', lang: 'ts', tags: ['clone', 'copy', 'deep', 'duplicate', 'object', 'immutable'], use: 'const copy = deepClone(state)', code: `export const deepClone = <T>(x: T): T => JSON.parse(JSON.stringify(x)) as T;\n` }),
  lib({ title: 'getPath — read a nested value by "a.b.c"', kind: 'object', lang: 'ts', tags: ['get', 'path', 'nested', 'dot', 'object', 'lookup', 'access'], use: 'getPath(obj, "user.address.city")', code: `export function getPath(obj: unknown, path: string): unknown {\n  return path.split('.').reduce<unknown>((o, k) => (o && typeof o === 'object' ? (o as Record<string, unknown>)[k] : undefined), obj);\n}\n` }),

  // ── async / function ──────────────────────────────────────────────────────
  lib({ title: 'throttle — run a function at most once per interval', kind: 'util', lang: 'ts', tags: ['throttle', 'rate', 'limit', 'scroll', 'interval', 'debounce', 'function'], use: 'const onScroll = throttle(handler, 100)', code: `export function throttle<T extends (...a: any[]) => void>(fn: T, ms: number): (...a: Parameters<T>) => void {\n  let last = 0;\n  return (...args: Parameters<T>) => {\n    const now = Date.now();\n    if (now - last >= ms) { last = now; fn(...args); }\n  };\n}\n` }),
  lib({ title: 'sleep — await a delay (Promise of ms)', kind: 'async', lang: 'ts', tags: ['sleep', 'delay', 'wait', 'pause', 'timeout', 'async', 'promise'], use: 'await sleep(500)', code: `export const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));\n` }),
  lib({ title: 'retry — retry an async function a few times', kind: 'async', lang: 'ts', tags: ['retry', 'attempt', 'resilient', 'async', 'backoff', 'fail', 'network'], use: 'await retry(() => fetchJson(url), 3)', code: `export async function retry<T>(fn: () => Promise<T>, times = 3, delayMs = 300): Promise<T> {\n  let err: unknown;\n  for (let i = 0; i < times; i++) {\n    try { return await fn(); } catch (e) { err = e; await new Promise((r) => setTimeout(r, delayMs * (i + 1))); }\n  }\n  throw err;\n}\n` }),
  lib({ title: 'memoize — cache a pure function by its args', kind: 'util', lang: 'ts', tags: ['memoize', 'cache', 'memo', 'performance', 'function', 'speed'], use: 'const fast = memoize(slow)', code: `export function memoize<A extends unknown[], R>(fn: (...a: A) => R): (...a: A) => R {\n  const cache = new Map<string, R>();\n  return (...args: A): R => {\n    const key = JSON.stringify(args);\n    if (!cache.has(key)) cache.set(key, fn(...args));\n    return cache.get(key) as R;\n  };\n}\n` }),
  lib({ title: 'once — call a function only the first time', kind: 'util', lang: 'ts', tags: ['once', 'single', 'init', 'guard', 'function', 'first'], use: 'const init = once(setup)', code: `export function once<A extends unknown[], R>(fn: (...a: A) => R): (...a: A) => R | undefined {\n  let done = false, val: R | undefined;\n  return (...args: A) => { if (!done) { done = true; val = fn(...args); } return val; };\n}\n` }),

  // ── date ──────────────────────────────────────────────────────────────────
  lib({ title: 'relativeTime — "3 minutes ago" from a date', kind: 'date', lang: 'ts', tags: ['relative', 'time', 'ago', 'date', 'timeago', 'humanize', 'since'], use: 'relativeTime(post.createdAt)', code: `export function relativeTime(d: Date | number): string {\n  const s = Math.floor((Date.now() - new Date(d).getTime()) / 1000);\n  const t: [number, string][] = [[60, 'second'], [60, 'minute'], [24, 'hour'], [7, 'day'], [4.35, 'week'], [12, 'month'], [Infinity, 'year']];\n  let n = s, i = 0, unit = 'second';\n  for (const [div, name] of t) { if (n < div) { unit = name; break; } n = Math.floor(n / div); unit = name; }\n  return n <= 1 ? 'just now' : n + ' ' + unit + 's ago';\n}\n` }),
  lib({ title: 'addDays — date N days from another', kind: 'date', lang: 'ts', tags: ['date', 'add', 'days', 'offset', 'calendar', 'future'], use: 'addDays(new Date(), 7)', code: `export function addDays(d: Date, days: number): Date {\n  const r = new Date(d);\n  r.setDate(r.getDate() + days);\n  return r;\n}\n` }),

  // ── validation ──────────────────────────────────────────────────────────
  lib({ title: 'isEmail — validate an email address', kind: 'validation', lang: 'ts', tags: ['email', 'validate', 'check', 'form', 'input', 'valid'], use: 'if (!isEmail(value)) showError()', code: `export const isEmail = (s: string): boolean => /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(s);\n` }),
  lib({ title: 'isUrl — check if a string is a valid URL', kind: 'validation', lang: 'ts', tags: ['url', 'validate', 'link', 'check', 'http', 'valid'], use: 'isUrl(input)', code: `export function isUrl(s: string): boolean {\n  try { new URL(s); return true; } catch { return false; }\n}\n` }),

  // ── dom / ui ──────────────────────────────────────────────────────────────
  lib({ title: 'copyToClipboard — copy text to the clipboard', kind: 'dom', lang: 'ts', tags: ['copy', 'clipboard', 'paste', 'button', 'dom', 'navigator'], use: 'await copyToClipboard(code)', code: `export const copyToClipboard = (text: string): Promise<void> => navigator.clipboard.writeText(text);\n` }),
  lib({ title: 'createEl — make a DOM element with props + children', kind: 'dom', lang: 'ts', tags: ['create', 'element', 'dom', 'append', 'render', 'node', 'html'], use: 'createEl("button", { textContent: "Go" })', code: `export function createEl<K extends keyof HTMLElementTagNameMap>(tag: K, props: Partial<HTMLElementTagNameMap[K]> = {}, children: (Node | string)[] = []): HTMLElementTagNameMap[K] {\n  const el = document.createElement(tag);\n  Object.assign(el, props);\n  for (const c of children) el.append(c);\n  return el;\n}\n` }),
  lib({ title: 'onClick — event delegation for many elements', kind: 'dom', lang: 'ts', tags: ['click', 'event', 'delegate', 'listener', 'dom', 'handler', 'selector'], use: 'onClick("button.del", (e, el) => …)', code: `export function onClick(selector: string, handler: (e: Event, el: Element) => void): void {\n  document.addEventListener('click', (e) => {\n    const el = (e.target as Element)?.closest(selector);\n    if (el) handler(e, el);\n  });\n}\n` }),

  // ── storage ────────────────────────────────────────────────────────────────
  lib({ title: 'storage — typed localStorage get/set (JSON)', kind: 'storage', lang: 'ts', tags: ['localstorage', 'storage', 'save', 'persist', 'load', 'json', 'offline'], use: 'storage.set("todos", items); storage.get("todos", [])', code: `export const storage = {\n  get<T>(key: string, fallback: T): T {\n    try { const v = localStorage.getItem(key); return v ? (JSON.parse(v) as T) : fallback; } catch { return fallback; }\n  },\n  set<T>(key: string, value: T): void { localStorage.setItem(key, JSON.stringify(value)); },\n  remove(key: string): void { localStorage.removeItem(key); },\n};\n` }),

  // ── data structures ──────────────────────────────────────────────────────
  lib({ title: 'Queue — a typed FIFO queue', kind: 'data-structure', lang: 'ts', tags: ['queue', 'fifo', 'enqueue', 'dequeue', 'data', 'structure', 'collection'], use: 'const q = new Queue<number>(); q.enqueue(1); q.dequeue()', code: `export class Queue<T> {\n  private items: T[] = [];\n  enqueue(x: T): void { this.items.push(x); }\n  dequeue(): T | undefined { return this.items.shift(); }\n  peek(): T | undefined { return this.items[0]; }\n  get size(): number { return this.items.length; }\n}\n` }),
  lib({ title: 'EventEmitter — subscribe/emit typed events', kind: 'data-structure', lang: 'ts', tags: ['event', 'emitter', 'pubsub', 'subscribe', 'emit', 'listener', 'observer'], use: 'const bus = new EventEmitter(); bus.on("x", fn); bus.emit("x", data)', code: `export class EventEmitter {\n  private map = new Map<string, ((...a: any[]) => void)[]>();\n  on(event: string, fn: (...a: any[]) => void): () => void {\n    const list = this.map.get(event) ?? [];\n    list.push(fn); this.map.set(event, list);\n    return () => this.map.set(event, (this.map.get(event) ?? []).filter((f) => f !== fn));\n  }\n  emit(event: string, ...args: any[]): void { for (const fn of this.map.get(event) ?? []) fn(...args); }\n}\n` }),
  lib({ title: 'LRUCache — a fixed-size least-recently-used cache', kind: 'data-structure', lang: 'ts', tags: ['lru', 'cache', 'memory', 'evict', 'limit', 'map', 'recent'], use: 'const c = new LRUCache<string, number>(100)', code: `export class LRUCache<K, V> {\n  private map = new Map<K, V>();\n  constructor(private max = 100) {}\n  get(key: K): V | undefined {\n    if (!this.map.has(key)) return undefined;\n    const v = this.map.get(key) as V; this.map.delete(key); this.map.set(key, v); return v;\n  }\n  set(key: K, value: V): void {\n    if (this.map.has(key)) this.map.delete(key);\n    this.map.set(key, value);\n    if (this.map.size > this.max) this.map.delete(this.map.keys().next().value as K);\n  }\n}\n` }),

  // ── game ──────────────────────────────────────────────────────────────────
  lib({ title: 'keyboardState — track which keys are held down', kind: 'game', lang: 'ts', tags: ['keyboard', 'keys', 'input', 'game', 'controls', 'wasd', 'arrow', 'held'], use: 'const keys = keyboardState(); if (keys.has("ArrowLeft")) …', code: `export function keyboardState(): Set<string> {\n  const keys = new Set<string>();\n  window.addEventListener('keydown', (e) => keys.add(e.key));\n  window.addEventListener('keyup', (e) => keys.delete(e.key));\n  return keys;\n}\n` }),
  lib({ title: 'vec2 — 2D vector add/sub/length helpers', kind: 'game', lang: 'ts', tags: ['vector', 'vec2', 'math', 'position', 'physics', 'game', 'movement', 'point'], use: 'add(pos, scale(dir, speed))', code: `export interface V2 { x: number; y: number; }\nexport const add = (a: V2, b: V2): V2 => ({ x: a.x + b.x, y: a.y + b.y });\nexport const sub = (a: V2, b: V2): V2 => ({ x: a.x - b.x, y: a.y - b.y });\nexport const scale = (a: V2, s: number): V2 => ({ x: a.x * s, y: a.y * s });\nexport const length = (a: V2): number => Math.hypot(a.x, a.y);\n` }),

  // ── color ──────────────────────────────────────────────────────────────────
  lib({ title: 'hexToRgb — parse a #hex color to {r,g,b}', kind: 'color', lang: 'ts', tags: ['color', 'hex', 'rgb', 'parse', 'convert', 'css'], use: 'hexToRgb("#3498db")', code: `export function hexToRgb(hex: string): { r: number; g: number; b: number } | null {\n  const m = /^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex.trim());\n  return m ? { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) } : null;\n}\n` }),

  // ── network ──────────────────────────────────────────────────────────────
  lib({ title: 'postJson — POST a JSON body and parse the JSON reply', kind: 'net', lang: 'ts', tags: ['post', 'json', 'fetch', 'http', 'api', 'request', 'send', 'network'], use: 'await postJson("/api/x", { name })', code: `export async function postJson<T = unknown>(url: string, body: unknown): Promise<T> {\n  const res = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });\n  if (!res.ok) throw new Error('HTTP ' + res.status);\n  return (await res.json()) as T;\n}\n` }),
];
